/**
 * Kiro Hook: Auto-generate test cases when user story is saved
 * 
 * Trigger: When a user story is created or updated in STLC Backlog
 * Action: Automatically generate test cases for the story
 * 
 * This hook demonstrates automation of testing workflows by
 * connecting user story creation with test case generation.
 */

module.exports = {
  name: 'Generate Test Cases from User Story',
  description: 'Automatically generate test cases when a user story is saved',
  
  trigger: {
    type: 'file-save',
    pattern: 'src/pages/StlcBacklog.jsx',
    condition: 'User story saved'
  },
  
  async execute(context) {
    const { userStory } = context;
    
    // Extract user story details
    const input = `
      Title: ${userStory.title}
      Description: ${userStory.description}
      Acceptance Criteria: ${userStory.acceptanceCriteria}
    `;
    
    // Call test case generation API
    const response = await fetch('http://localhost:3001/api/generate-test-cases', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ input, type: 'functional' })
    });
    
    const { testCases } = await response.json();
    
    // Save generated test cases to library
    for (const testCase of testCases) {
      await context.saveToLibrary({
        ...testCase,
        linkedStory: userStory.id,
        autoGenerated: true
      });
    }
    
    return {
      success: true,
      message: `Generated ${testCases.length} test cases for story: ${userStory.title}`,
      testCases
    };
  }
};
