/**
 * Kiro Hook: Auto-generate test scripts from test cases
 * 
 * Trigger: When test cases are saved to library
 * Action: Generate automation scripts in multiple frameworks
 * 
 * This hook automates the conversion of manual test cases
 * into executable automation scripts.
 */

module.exports = {
  name: 'Generate Scripts from Test Cases',
  description: 'Automatically generate automation scripts when test cases are saved',
  
  trigger: {
    type: 'library-save',
    itemType: 'test-case'
  },
  
  async execute(context) {
    const { testCase } = context;
    const frameworks = ['selenium', 'cypress', 'playwright'];
    const scripts = {};
    
    // Generate script for each framework
    for (const framework of frameworks) {
      const scenario = `
        Test: ${testCase.title}
        Steps: ${testCase.steps.join(', ')}
        Expected: ${testCase.expectedResult}
      `;
      
      const response = await fetch('http://localhost:3001/api/generate-test-script', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ scenario, framework })
      });
      
      const { script } = await response.json();
      scripts[framework] = script;
    }
    
    // Save scripts to library
    await context.saveToLibrary({
      type: 'script-collection',
      testCaseId: testCase.id,
      scripts,
      autoGenerated: true
    });
    
    return {
      success: true,
      message: `Generated scripts for ${frameworks.length} frameworks`,
      frameworks
    };
  }
};
